name: Build Wasm

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Wasm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: numworks/setup-emscripten@latest

      - run: emcmake cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF
      - run: cmake --build build --config Release --parallel $(nproc)
      - run: cmake --install build --config Release --prefix pkg

      - uses: actions/upload-artifact@v4
        with:
          name: Wasm
          path: pkg
