name: Coverage

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    timeout-minutes: 10
    name: "Coverage"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM 19
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 200
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-19 200
          sudo update-alternatives --install /usr/bin/llvm-profdata llvm-profdata /usr/bin/llvm-profdata-19 200
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV

      - run: ./tools/coverage-generate.sh sleipnir_test

      - uses: actions/upload-artifact@v4
        with:
          name: Coverage report
          path: ./build-coverage/coverage-line-by-line-sleipnir_test.html

      - name: Write to job summary
        run: |
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          cat ./build-coverage/coverage-report-sleipnir_test.txt >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
