name: Documentation

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    name: "Doxygen"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - run: mkdir build

      - name: Make GCC 14 the default toolchain (Linux)
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.11
        # sccache doesn't work with MSBuild
        if: runner.os != 'Windows'

      - uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - run: pip install pybind11-mkdoc==3.0.0
      - run: sudo apt-get install -y doxygen
      - run: ./generate_website.py
        working-directory: ./docs

      - uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: docs/build/html
